name: Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited]
    branches:
      - master

env:
  npm_config_cache: .cache/npm
  node_version: 13.x


jobs:
  commit_lint:
    name: Lint commit messages
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.OTTO_TOKEN }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v2
        with:
          failOnWarnings: true

      - uses: amannn/action-semantic-pull-request@v2.1.0

  # Always lint
  checks_and_tests:
    name: Linting and tests
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.OTTO_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ env.node_version }}

      - name: Configure npm cache
        uses: actions/cache@v2
        with:
          path: ${{ env.npm_config_cache }}
          key: npm-${{ hashFiles('./package*.json') }}
          restore-keys: |
            npm

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run unit tests
        run: npm run test

  auto_merge_dependabot:
      name: Auto-approve dependabot pull requests
      runs-on: ubuntu-latest
      needs: [checks_and_tests, commit_lint]

      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'

      steps:
        - name: Auto-approve
          uses: hmarr/auto-approve-action@v2.0.0
          with:
            github-token: ${{ secrets.OTTO_TOKEN }}

        - name: Auto-merge
          uses: "pascalgn/automerge-action@v0.12.0"
          env:
            GITHUB_TOKEN: "${{ secrets.OTTO_TOKEN }}"
            MERGE_LABELS: ""
            MERGE_METHOD: squash
