name: Release

on:
  push:
    tags:
      - 'v*'

env:
  YARN_CACHE_FOLDER: .cache/yarn
  node_version: 14.x
  # yarn needs *some* value in NODE_AUTH_TOKEN to work - it doesn't have
  # to be valid so long as you're not communicating with the registry
  NODE_AUTH_TOKEN: XXX

jobs:
  publish_npm:
    name: Publish npm package
    runs-on: ubuntu-latest
    if: github.event.base_ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "${{ env.node_version }}"
          registry-url: https://registry.npmjs.org/

      - name: Configure yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ env.YARN_CACHE_FOLDER }}
          key: yarn-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            yarn

      - name: Install dependencies
        run: yarn install

      - name: Publish npm package
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
