name: Release

on:
  push:
    tags:
      - 'v*'

env:
  npm_config_cache: .cache/npm
  node_version: 13.x

jobs:
  publish_npm:
    name: Publish npm package
    runs-on: ubuntu-latest
    if: github.event.base_ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2.1.1
        with:
          node-version: "${{ env.node_version }}"
          registry-url: https://registry.npmjs.org/

      - name: Configure npm cache
        uses: actions/cache@v2
        with:
          path: ${{ env.npm_config_cache }}
          key: npm-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            npm

      - name: Install dependencies
        run: npm install

      - name: Publish npm package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
