name: Bump Version

on:
  push:
    branches:
      - master

jobs:
    update_version:
      name: Update Version
      runs-on: ubuntu-latest
      # This avoids the workflow triggering itself when the version changes are pushed
      if: "!startsWith(github.event.head_commit.message, 'chore')"

      steps:
        - name: Check out code
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.OTTO_TOKEN }}
            fetch-depth: 0

        - name: Configure Otto
          run: |
            git config --local user.email "otc-builder@outcome.co"
            git config --local user.name "Otto the Bot"

        - name: Bump version
          id: bump_version
          uses: 'outcome-co/action-update-version@master'

        - name: Push new version
          if: ${{ steps.bump_version.outputs.updated == 'true' }}
          run: git push && git push --follow-tags --tags
